FROM public.ecr.aws/docker/library/python:3.9-slim-bullseye

WORKDIR /app

ENV FLASK_APP=app.py 

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# Copy the script that sets up the environment
COPY setup.sh /setup.sh

# Make the script executable
RUN chmod +x /setup.sh

# Run the script when the container starts
CMD ["/setup.sh"]